default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["API_KEY"], # Assuming API_KEY contains the content of the .p8 file
      duration: 1200, # optional
      in_house: false # optional
    )

    # Increment the build number
    increment_build_number(xcodeproj: "Runner.xcodeproj")

    pilot(api_key: api_key)
  end
end
