name: Deploy to TestFlight

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/flutter-ios-deploy.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel env pull --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'

      - name: Install Fastlane
        run: gem install bundler && bundle install
        working-directory: ./app/ios

      - run: flutter clean
        working-directory: ./app

      - run: flutter pub get
        working-directory: ./app

      - run: flutter pub run build_runner build
        working-directory: ./app

      - run: flutter build ios --release --no-codesign
        working-directory: ./app

      - name: CocoaPods Install
        run: pod install
        working-directory: ./app/ios

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: beta --verbose
          subdirectory: app/ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
